export interface Soldprod {
    id: string,
    codigo: string,
    clasificacion: string,
    descripcion: string,
    marca: string,
    precioCompra: number,
    costoCompra: number,
    cantidad: number,
    total: number,
    totalFac: number,
    precioVenta: number,
    precioFinal: number,
    inventario: number,
    totalAcumulado: number,
    costoUnitario: number,
    fecha: any,
    date: Date,
    tipo: string
}